### ISSUE TITLE
client.select_cells(where='protein', ...) example?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-api-py-client#17]
I've tried a couple different protein abbreviations. What's a working example of finding cells by protein?

**Comment by SFD5311** [comment]
These queries aren't currently working because there's not currently CODEX data loaded on the dev instance.  There will be shortly and I will follow up here and on Slack with some examples when there is.

**Comment by mccalluc** [comment]
@SFD5311 : No hurry, but wanted to check if this had been implemented, but I just missed it.

**Comment by SFD5311** [comment]
It hasn't yet, but I am still actively working on it and will let you know when it has.
