### ISSUE TITLE
Should query always be a list, even if just single valued?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-api-py-client#19]
It works to send single values... is it not safe to assume this will continue to work on the backend? ... or just as a matter of sdk design, would it be better if the type of the parameter is consistent?

These have the same result:
```python
>>> a_b_union_operator = \
...     client.select_cells(where='dataset', has=a_uuid) \
...     | client.select_cells(where='dataset', has=b_uuid)
>>> a_b_union_query = \
...     client.select_cells(where='dataset', has=[a_uuid, b_uuid])
```

**Comment by SFD5311** [comment]
I agree that consistency is desirable in the long term, and I probably wouldn't assume that it will continue to work on the back end.  This is largely a function of the fact that the API and the browser based interface receive inputs as slightly different types, and the functions that process the input do some handling to accommodate this.

**Comment by mccalluc** [comment]
Ok: I'll validate input on our side and require a list.
