### ISSUE TITLE
Set complement not right?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-api-py-client#20]
```python
>>> from cells_api_py_client import Client
>>> client = Client('https://cells.dev.hubmapconsortium.org/api/')
>>> a_uuid = '68159e4bd6a2cea1cd66e8f3050cfcb7'
>>> b_uuid = 'e8d642084fc5ec8b5d348ebab96a4b22'
>>> a_b_cells = client.select_cells(where='dataset', has=[a_uuid, b_uuid])
>>> len(a_b_cells)
8795
>>> vim_cells = client.select_cells(where='gene', has='VIM > 0.5', genomic_modality='rna')
>>> len(vim_cells)
33729
>>> a_b_vim_cells = a_b_cells & vim_cells
>>> len(a_b_vim_cells)
5164
```
... that much is good.

The complement is very large, as we would expect:
```python
>>> not_vim_cells = ~ vim_cells
>>> len(not_vim_cells)
134142
```

but:
```python
>>> a_b_and_not_vim = a_b_cells & not_vim_cells
>>> len(a_b_and_not_vim)
8795
```
Expected 8795 - 5164 = 3631.

**Comment by SFD5311** [comment]
This is definitely a bug.  I will look into it ASAP.

**Comment by SFD5311** [comment]
I've only been able to reproduce this when taking the intersection of two sets, one of which was the result of a previous negation (a la set subtraction).  For the moment, I've added an end point for computing set differences (at /api/difference) which is giving the expected results for this example.

**Comment by mccalluc** [comment]
Cool: I'll use that instead, and get rid of the complement magic method.
