### ISSUE TITLE
cluster detail keys should be a superset?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-api-py-client#22]
I would expect the keys from `details` to be a superset of the plain list, but that doesn't seem to be the case: For clusters, `cluster_method` and `cluster_data` are missing. Problem?
```python
>>> clusters_with_gene = client.select_clusters(where='gene', has='CASTOR2')
>>> assert len(clusters_with_gene) > 0

>>> clusters_with_gene.get_list(1)[0].keys()
dict_keys(['cluster_method', 'cluster_data', 'grouping_name', 'dataset'])

>>> clusters_with_gene.get_details(1)[0].keys()
dict_keys(['grouping_name', 'dataset', 'values'])
```

**Comment by SFD5311** [comment]
Sorry, forgot to mention that this should be fixed with:
https://github.com/hubmapconsortium/cross_modality_query/commit/4cfba8f30c895714337abafdb344b4889f781cdd

**Comment by mccalluc** [comment]
Yep: doc test updated in #33.
