### ISSUE TITLE
Page through results? `offset` in addition to `limit`?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-api-py-client#29]
I think we need to allow users to page through large result sets: In addition to `limit`, should there be an `offset`, or something like that?

**Comment by SFD5311** [comment]
Yeah, this makes sense and can be done.  Will update here when it's ready.

**Comment by SFD5311** [comment]
To clarify, is the suggestion that to retrieve 20 results starting with result 50, the parameters should be "offset":50, "limit":20 or "offset":50, "limit":70?

**Comment by mccalluc** [comment]
@SFD5311 : I believe the standard semantics are for "limit" to be the *number* of records returned. In [postgres](https://www.postgresql.org/docs/8.1/queries-limit.html) for example. So, in your example, `"offset":50, "limit":20`.

**Comment by SFD5311** [comment]
Implemented with:
https://github.com/hubmapconsortium/cross_modality_query/commit/4452bbf0e50bd0b432fca4963bdbc296e8f91cc0
