### ISSUE TITLE
Use the new fast gene expression API

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-api-py-client#67]
@SFD5311 - Can you provide details?

**Comment by SFD5311** [comment]
Sure:
The new end points will take a set token, a list of variable identifiers (i.e. gene symbols), and a data modality ('rna', 'atac', 'codex') as parameters and will return a JSON serialized dictionary mapping from each identifier in the input set to the corresponding list of values associated with that gene in the set specified by the token provided.

So for example, a post request to URL '/api/cellvaluesevaluation/ with parameters:
set_token='example_cell_set_token'
data_modality='rna'
var_ids=['VIM', 'SOX2', 'CD4']

Would return output like:
{'VIM':[1,0,2...], 'SOX2':[1,3,1...], 'CD4':[2, 0, 1...]}

**Comment by mccalluc** [comment]
@SFD5311 -- Thanks! ... From your side, would it be hard to make the keys the cell IDs, with the expression levels for each requested gene in the list... or return a dict instead of a list? (Essentially, transpose.) If that would be awkward on your side, not a problem to do it on our side, but thought I'd ask.

**Comment by SFD5311** [comment]
I don't think it'd be terribly difficult in terms of engineering penalty, but I do suspect that there would be a pretty significant run-time penalty.

To be clear, the lists associated with each gene are not necessarily ordered, and the 0th item in the VIM list in the above example doesn't necessarily correspond to the 0th item in the SOX2 list.  That's a pretty large part of how we're getting this speed up.  So they'd be suitable for a histogram, or computing bulk 1 variable statistics, but not for plotting correlation or covariance between two genes, for example.

I can experiment with returning the values data in a more structured form and see how much of the performance gain can be retained, but I'm not extremely optimistic.

**Comment by mccalluc** [comment]
oh... unordered lists per gene probably won't be that useful. How about if we put this on hold to see more about what kind of visualizations are being planned? Thanks.

**Comment by SFD5311** [comment]
@mccalluc I did have an idea I wanted to try out, and in preliminary testing, this method provides dicts per cell as you described above and takes about 7 seconds per gene per scRNA dataset, which is definitely not as fast as the unordered lists per gene, but is still substantially faster than the current method.  In any case, like you said, I won't pursue any further until we have a good idea of what kinds of visualizations are planned.

**Comment by mccalluc** [comment]
(Just asked on slack what the status is.)

**Comment by mccalluc** [comment]
After talking with Sean, this particular direction didn't turn out to be useful. Closing.
