### ISSUE TITLE
When can genomic_modality='atac' be used?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-api-py-client#8]
I was expecting to be able to be able to replace `rna` with `atac`:
```
>>> client.select_cells(where='gene', has='VIM>0', genomic_modality='atac')
Traceback (most recent call last):
...
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by SFD5311** [comment]
Once I load the ATAC data into the dev database instance, that will be doable.

**Comment by mccalluc** [comment]
@SFD5311 : Can you update here when the data is available?

**Comment by SFD5311** [comment]
Yes, definitely will do.

**Comment by SFD5311** [comment]
ATAC data are loaded onto the dev instance now.
