### ISSUE TITLE
How are organ names generated? Will they align?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-api-py-client#9]
How are organ names generated? Will they align with names from other parts of the system? For instance, I think it makes sense to just have a single `Kidney` here, but in other parts of the system it's two separate codes.

**Comment by SFD5311** [comment]
In general, organs are resolved from dataset UUIDs using search-API.  Per your suggestion following the data portal meeting a while back, I then introduced a subsequent step which eliminates Left and Right distinctions for the Kidney, Lung, Bronchi, and numbers for the Lymph Nodes.

**Comment by mccalluc** [comment]
@SFD5311 : Sounds good: On our side, that same mapping happens at index-time. If the rules ever get more complicated, there should be some utility that we share, but for now, I think it' easiest just to have the same thing being done in two different places in the code base. Closing.
